# Author: Paul Graydon <untimely.creation97@proton.me>

inherits = "tokyonight"

"ui.explorer.file" = { fg = "foreground" }
"ui.explorer.dir" = { fg = "blue" }
"ui.explorer.exe" = { fg = "foreground" }
"ui.explorer.focus" = { modifiers = ["reversed"] }
"ui.explorer.unfocus" = { bg = "background_highlight" }

[palette]
border = "#1d202f"
bg = "#24283b"
bg-inlay = "#233745"
bg-highlight = "#373d5a"
bg-menu = "#1f2335"
bg-visual = "#2e3c64"
border-highlight = "#29a4bd"
